[package]
name = "pilipala-kernel"
version = "0.0.1"
edition = "2021"
description = "Kernel of pilipala"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
